////  TEACHERS
export const GET_TEACHERS = 'GET_USERS';
export const GET_TEACHER_BY_NAME = ' GET_TEACHER_BY_NAME';
export const ADD_TEACHER = ' ADD_TEACHER';
export const FILTER_TEACHERS = 'FILTER_TEACHERS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
